```{r}
pacman::p_load(dotenv, tidyverse, ggplot2, httr, jsonlite)
load_dot_env(file = "../.env")
```


# Simple non-bias-controlled average results over projects

```{r}
NOTION_KEY = Sys.getenv(c("NOTION_API_KEY"))

payload = '{"filter":{"property":"sprint","relation":{"contains":"ceee7fa0b924421a97c50089de27bd76"}}}'
ask <- POST(
  url = 'https://api.notion.com/v1/databases/9d6bdef615ad4c878005ac5cedd11a71/query',
  add_headers("Authorization" = paste("Bearer", NOTION_KEY),
              "Notion-Version" = "2022-06-28",
              "Content-Type" = "application/json"),
  body = payload
)
stop_for_status(ask)

df <- fromJSON(rawToChar(ask$content))$results %>% 
  unnest(cols=properties) %>% 
  select(sprint, everything())

df %>% 
  unnest(c(topic, ais, methods, project, sprintdate, judge), names_sep = "_") %>% 
  unnest(c(sprintdate_rollup, project_title, judge_people), names_sep="_") %>% 
  drop_na(topic_number) %>% 
  group_by(project_title_plain_text) %>%
  summarise(
    topic = mean(topic_number, na.rm=T),
    ais = mean(ais_number, na.rm=T),
    methods = mean(methods_number, na.rm=T),
    count = n()
  ) %>% 
  mutate(
    avg = (topic + ais + methods) / 3
  ) %>% 
  arrange(desc(avg))

```



